import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { AppColors, FontFamily, MaxContentWidth, Radius, Shadow, Spacing } from '@/constants/theme';

const sections = [
  { title: 'Information LifeBook keeps', body: 'Account identity and authentication status; family membership, expiring invitation metadata, and managed profiles; people, relationships, memories, chapters, reminders, consent records, privacy settings, audit events, and selected photos.' },
  { title: 'How information is used', body: 'Information is used only to provide the private family archive, synchronize it across authorized devices, enforce family permissions, create exports, and complete account-lifecycle requests.' },
  { title: 'Service providers', body: 'Firebase provides Authentication, Firestore, Cloud Storage, and privileged deletion functions. Vercel hosts the static web experience. LifeBook does not include advertising, social-media, data-broker, or behavioral-tracking SDKs.' },
  { title: 'Visibility and child safety', body: 'Protected records are family-only. LifeBook has no public profiles, followers, public discovery, direct messaging, or precise-location collection. Managed child profiles cannot grant permissions.' },
  { title: 'Export and deletion', body: 'A verified account holder can export family data as machine-readable JSON. Account deletion requires recent password confirmation and covers Authentication, user records, family records controlled by a sole owner, and private family media.' },
  { title: 'Retention', body: 'Active and archived records remain until authorized deletion. Content-free deletion receipts expire after 30 days. Temporary export files use the device cache or browser download location. Provider-managed backups follow the provider lifecycle and are not accessible in LifeBook.' },
  { title: 'Recovery and support', body: 'Deletion is irreversible. Owners with other family members must transfer ownership first. Account recovery uses Firebase email/password recovery without exposing family information. Final publisher and privacy contact details will be added before public store release.' },
  { title: 'Family invitations', body: 'Invitation links expire after seven days, are bound to one verified email address, and can be revoked by the family owner. Expired invitation metadata is removed automatically. Only accepted verified members can read family records.' },
  { title: 'Device reminder notifications', body: 'Reminder alerts are optional and scheduled locally on each opted-in iOS or Android device. Visible alerts use generic wording. LifeBook stores the opt-in preference and native schedule identifiers on the device, does not upload a push token, and does not send reminder details to a notification server.' },
];

export default function PrivacyPolicyScreen() {
  const router = useRouter();
  return <SafeAreaView style={styles.safeArea} edges={['top', 'bottom']}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.header}><Pressable accessibilityLabel="Go back" onPress={() => router.canGoBack() ? router.back() : router.replace('/')} style={styles.iconButton}><Ionicons name="arrow-back" size={24} color={AppColors.ink} /></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>LifeBook privacy notice</Text><Text style={styles.title}>Data practices & retention</Text><Text style={styles.updated}>Engineering disclosure · August 1, 2026</Text></View></View><View style={styles.intro}><Ionicons name="shield-checkmark" size={31} color={AppColors.mint} /><Text style={styles.introTitle}>Private by design</Text><Text style={styles.introText}>This disclosure describes the behavior implemented in the current LifeBook application. A final publisher identity, contact address, and legal/child-privacy review are required before public store release.</Text></View>{sections.map((section) => <View key={section.title} style={styles.card}><Text style={styles.sectionTitle}>{section.title}</Text><Text style={styles.body}>{section.body}</Text></View>)}<Pressable accessibilityRole="button" onPress={() => router.push('/delete-account')} style={({ pressed }) => [styles.deleteLink, pressed && styles.pressed]}><Ionicons name="trash-outline" size={20} color={AppColors.danger} /><Text style={styles.deleteText}>Open public account-deletion request</Text></Pressable></ScrollView></SafeAreaView>;
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: AppColors.cloud }, content: { width: '100%', maxWidth: MaxContentWidth, alignSelf: 'center', padding: Spacing.xl, paddingBottom: Spacing.section, gap: Spacing.lg }, header: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.lg, marginBottom: Spacing.sm }, iconButton: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: Radius.full, backgroundColor: AppColors.paper, borderWidth: 1, borderColor: AppColors.border }, headerCopy: { flex: 1 }, eyebrow: { color: AppColors.violet, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.8 }, title: { color: AppColors.ink, fontFamily: FontFamily?.bold, fontSize: 28, lineHeight: 34, fontWeight: '800', marginTop: 3 }, updated: { color: AppColors.slate, fontSize: 11, marginTop: 5 }, intro: { alignItems: 'center', gap: Spacing.sm, padding: Spacing.xxl, borderRadius: Radius.xl, backgroundColor: AppColors.hero, ...Shadow.card }, introTitle: { color: AppColors.onDark, fontSize: 19, fontWeight: '800' }, introText: { color: '#C9D0E0', fontSize: 13, lineHeight: 20, textAlign: 'center' }, card: { gap: Spacing.sm, padding: Spacing.xl, borderRadius: Radius.lg, backgroundColor: AppColors.paper, borderWidth: 1, borderColor: AppColors.border }, sectionTitle: { color: AppColors.ink, fontSize: 16, fontWeight: '800' }, body: { color: AppColors.inkMuted, fontSize: 14, lineHeight: 22 }, deleteLink: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm, borderRadius: Radius.lg, backgroundColor: AppColors.blushSoft }, deleteText: { color: AppColors.danger, fontSize: 14, fontWeight: '800' }, pressed: { opacity: 0.65 },
});
